[package]
name = "websocket-server-snake"
version = "0.0.1"
authors = ["Tikitko <bns.6587@gmail.com>"]
edition = "2018"

[dependencies]
snake = { path = "../snake" }
uuid = "0.8.1"
futures = "0.3.5"
bytes = "0.5.6"
actix = "0.10.0"
actix-web = "3.0.2"
actix-web-actors = "3.0.0"